### ISSUE TITLE
Git User Credentials do not get saved when created

### ISSUE THREAD

**Issue by rainug** [PTCInc/thingworx-gitbackup-extension#58] opened 2024-05-17 07:27 UTC
The git user credentials disappear when the system is restarted.

![Screenshot 2024-05-17 092638](https://github.com/PTCInc/thingworx-gitbackup-extension/assets/55584136/1747235c-519c-4f9a-a619-9879e6fdaeca)

**Comment by vrosu** [comment] 2024-06-05 19:29
Thanks for reporting this bug @rainug . The issue is caused by the incorrect method of setting a property in the code, specifically due to the fact that I'm deleting rows directly on the infotable property, and that action does NOT trigger the persistence to database.

**Comment by vrosu** [comment] 2024-06-05 21:09
@rainug fixed in [5.0.1 release](https://github.com/PTCInc/thingworx-gitbackup-extension/releases/tag/V5.0.1-9.3 )

**Closed as completed by vrosu** 2024-06-05 21:09 UTC
Labels: bug, work in progress
